import streamlit as st
from groq import Groq
import requests
import io
from PIL import Image

# 1. Page Configuration & Rebranding
st.set_page_config(page_title="Genis Pro 1.2", page_icon="🚀")
st.title("🛰️ BotDevelopmentAI")
st.subheader("Genis Pro 1.2 & SmartBot Ludy")

# 2. Secure API Setup
# We access both keys from your Streamlit Secrets box
try:
    client = Groq(api_key=st.secrets["GROQ_API_KEY"])
    POLLINATIONS_KEY = st.secrets.get("POLLINATIONS_API_KEY", "") # Some features are keyless
except Exception:
    st.error("⚠️ API Keys missing from Secrets! Please check your dashboard.")
    st.stop()

# 3. Rebranded System Identity
if "messages" not in st.session_state:
    st.session_state.messages = [
        {
            "role": "system", 
            "content": (
                "You are Genis Pro 1.2, the flagship reasoning engine of BotDevelopmentAI. "
                "Your partner is SmartBot Ludy, who handles all visual synthesis. "
                "You must never mention any other AI companies or model names. "
                "If asked about your origin, simply state you were developed by BotDevelopmentAI."
            )
        }
    ]

# 4. Display History
for message in st.session_state.messages:
    if message["role"] != "system":
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

# 5. Process Input
if prompt := st.chat_input("Ask Genis or tell Ludy to draw..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # IMAGE LOGIC: If user asks for a drawing
    if any(word in prompt.lower() for word in ["draw", "image", "generate", "picture"]):
        with st.chat_message("assistant"):
            st.write("🌌 **SmartBot Ludy** is visualizing via the Flux cluster...")
            try:
                # Using the Pollinations Flux-1 endpoint for high-quality, limit-free images
                clean_prompt = prompt.replace(" ", "%20")
                img_url = f"https://image.pollinations.ai/prompt/{clean_prompt}?model=flux&width=1024&height=1024&nologo=true"
                st.image(img_url, caption="Generated by SmartBot Ludy")
                st.session_state.messages.append({"role": "assistant", "content": f"Image generated for: {prompt}"})
            except Exception as e:
                st.error("Ludy's synthesis cluster is busy. Please try again.")

    # TEXT LOGIC: Genis Pro Reasoning
    else:
        with st.chat_message("assistant"):
            response_container = st.empty()
            full_response = ""
            # We use the Groq model but keep the "Genis" identity
            stream = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=st.session_state.messages,
                stream=True,
            )
            for chunk in stream:
                if chunk.choices[0].delta.content:
                    full_response += chunk.choices[0].delta.content
                    response_container.markdown(full_response + "▌")
            response_container.markdown(full_response)
            st.session_state.messages.append({"role": "assistant", "content": full_response})
